data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
apiVersion: v1
kind: Secret
metadata:
  name: azuredevprj2aks
---
data:
  host.master: Yk1Ia1pjWjZXa2VnWDVuVkJMcVIyYVFGNEJhUXVDN1VRbTkyL1JSaDNVRjBPd3JvQmJHQUx3PT0=
  host.function.default: a2hRMEhGM0g4d3dOSmVJWFljOHNwQkpKWkNqN3BCWG5icEpSUU5vTkJob1hGSFp4c2NmNkZ3PT0=
  host.systemKey.default: WnoyRy9sakRPamdBWVdxYUhqS3AxUjJMYzRDTmpzQmF5M2pCcUJxM3ZOU0J4Vm9IZnlrMzRBPT0=
  functions.createadvertisement.default: eU5ZUldpcW85NURpMlRuOVduazNuem54Y2ZOY0YxamxFdHpkU2pnV3JRY0I0VVh1MEVVQmpRPT0=
  functions.deleteadvertisement.default: YWxjYjhHRlRMMTRFTWxrMndhSGFTMXJzWE4xY0kxa3RZMFNBTkhkNHprVnlxcVNubktTVWJnPT0=
  functions.getadvertisement.default: bFFYRWw1UXlCQW1UYmRDbW92OWpIaVNyTzYxY095RDkvWHlQcVFEOWFEZ3d3MXdKOTBwNk1nPT0=
  functions.getadvertisements.default: bDh6SmJzcWpJNFZuOUtEQ0gyZFV3YVB4TWQ2emRSejRnY1U2SThKdjB2d0tuc1VEOEJ6YmhRPT0=
  functions.getpost.default: UUJTYU5zM1MxTWtWVnRraHhqNmo1cmhzbWg2MENPaFRWUW1FbnRtVENRUGNTbHg2UTdZVVV3PT0=
  functions.getposts.default: RzNPM1pNajhKRWNBUWE5QmFzdW9EZTdQSGVWWnFSYnNGYXVDYXZONjhQa2NIcWFoeGhVM2xRPT0=
  functions.updateadvertisement.default: bmFIVFY5T1lPU05JYUFXcndQblpNdjFTLzBGWXBuZW1XWmE0ZkEybWgxMjMwMmR5SnhJNWNRPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-azuredevprj2aks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azuredevprj2aks-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: azuredevprj2aks-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azuredevprj2aks-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: azuredevprj2aks-http
spec:
  selector:
    app: azuredevprj2aks-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredevprj2aks-http
  labels:
    app: azuredevprj2aks-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azuredevprj2aks-http
  template:
    metadata:
      labels:
        app: azuredevprj2aks-http
    spec:
      containers:
      - name: azuredevprj2aks-http
        image: azuredevprj2funcreg.azurecr.io/azuredevprj2docker:v1
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-azuredevprj2aks
        envFrom:
        - secretRef:
            name: azuredevprj2aks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: azuredevprj2aks-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredevprj2aks
  labels:
    app: azuredevprj2aks
spec:
  selector:
    matchLabels:
      app: azuredevprj2aks
  template:
    metadata:
      labels:
        app: azuredevprj2aks
    spec:
      containers:
      - name: azuredevprj2aks
        image: azuredevprj2funcreg.azurecr.io/azuredevprj2docker:v1
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: azuredevprj2aks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: azuredevprj2aks-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azuredevprj2aks
  labels: {}
spec:
  scaleTargetRef:
    name: azuredevprj2aks
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

